name: gan-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - jupyterlab=2.2.9
  - nodejs=10.13.0
  - notebook=6.1.5
  - numpy=1.19.4
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - pip=20.3.3
  - python-graphviz=0.16
  - pip:
    - typer==0.3.2
    - pydot=1.4.1
    - pydotplus=2.0.2
    - ipywidgets==7.5.1
    - widgetsnbextension==3.5.1
