name: gan-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.2.9
  - nodejs=10.13.0
  - notebook=6.1.5
  - numpy=1.19.4
  - python=3.7.9
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - pip:
    - typer==0.3.2
    - ipywidgets==7.5.1
    - widgetsnbextension==3.5.1
